### ISSUE TITLE
Criar V2 do Rich Picture geral

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#10]
## Descrição da Issue
Criar segunda versão do rich picture feito em sala, em formato digital, utilizando imagens feitas manualmente através de uma mesa digitalizadora

### Tasks:
- [x] Fazer imagens
- [x] Montar Rich Picture no figma

**Comment by Phe0** [comment]
![Group 2](https://user-images.githubusercontent.com/31973465/55280823-aa63f780-5309-11e9-872a-b298fec8f190.png)

**Comment by Phe0** [comment]
Versão com fundo
![Group 2](https://user-images.githubusercontent.com/31973465/55280870-4a218580-530a-11e9-9cd1-d3c274d61708.png)

**Comment by Phe0** [comment]
Versão com fundo
![Group 3](https://user-images.githubusercontent.com/31973465/55280890-8a810380-530a-11e9-9b36-eb949ecd617f.png)

**Comment by Phe0** [comment]
Correção
![Group 3 (1)](https://user-images.githubusercontent.com/31973465/55280952-991bea80-530b-11e9-8661-8d7c3b1eb3ca.png)

**Comment by youssef-md** [comment]
Ficou muito bom @Phe0 parabéns!

**Comment by rogerioo** [comment]
Ficou sensacional @Phe0, parabéns!
