### ISSUE TITLE
Rich Picture Gamificação

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#11]
## Descrição da Issue
Montar um rich picture que no lugar de mostrar como os elementos envolvidos com o app interagem, como os elementos dentro do app motivam o usuário a realizar suas tarefas, baseando-se na literatura do Yu-Kai-Chou

### Tasks:
- [x] Copiar imagens 
- [x] Montar Rich Picture

**Comment by devsalula** [comment]
V1 do RP da Gamificação
![RichPictureGamification](https://user-images.githubusercontent.com/35435199/55292927-c11c5400-53c6-11e9-86f8-8d8ccdd1ac0e.jpg)

**Comment by Phe0** [comment]
Não sei se é bom escrever quais são os core drives na lateral do octogono, pra ficar mais entendível pra quem não sabe do q se trata

**Comment by devsalula** [comment]
@Phe0 pensei nisso. Mas acho que pode ficar muito bagunçado. Estava pensando em colocar o Octalysis do lado da apresentação do RP para compará-los e explicar os cores que mais se exaltam dentro da Gamificação.

**Comment by EsioFreitas** [comment]
esta otimo @devsalula
