### ISSUE TITLE
Montar V2 da argumentação da escolha de tema

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#13]
## Descrição da Issue
Montar segunda versão da argumentação feita para a escolha do tema do grupo, dessa vez incluindo os argumentos utilizados para os outros apps levantados

### Tasks:
- [ ] Pesquisar sobre dissipação de conflitos no modelo argumentativo 
- [ ] Levantar Proposições
- [ ] Inserir conflitos, inferências e preferências

**Comment by EsioFreitas** [comment]
Vou ficar responsável por essa issue
