### ISSUE TITLE
Pesquisar sobre diagrama de argumentação

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#15]
## Descrição da Issue
Entregar um documento de pesquisar sobre melhores práticas de diagrama de argumentação para entregar artefatos mais elaborados.

**Comment by Phe0** [comment]
o entregável é um documento ?
É bom especificar na issue

**Comment by EsioFreitas** [comment]
Pronto

**Comment by EsioFreitas** [comment]
![image](https://user-images.githubusercontent.com/34384624/55281128-b0a8a280-530e-11e9-90db-dab5cc430b8e.png)

**Comment by EsioFreitas** [comment]
[Cavalcante - TCC - ACE-CAST.pdf](https://github.com/requisitos-habitica/Habitica/files/3025900/Cavalcante.-.TCC.-.ACE-CAST.pdf)

**Comment by EsioFreitas** [comment]
No zip de mais conteúdo dos professores tem esse tcc que explica tudo. Muito bom!!
