### ISSUE TITLE
Diagrama de argumentação das funcionalidades que não estão dentro do escopo 

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#16]
# Issue Template

## Descrição da Issue
Fazer um diagrama que mostra porque de não escolhermos certas funcionalidades para o escopo do projeto.

## Funcionalidades

- [x] Time;
- [x] Guildas.

**Comment by Phe0** [comment]
coloca aqui quais as funcionalidades @EsioFreitas

**Comment by EsioFreitas** [comment]
Pronto.

**Comment by gabrielalbino** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/30835149/55291388-89a4ac00-53b4-11e9-8f7a-bef439c8fe7b.png)
@EsioFreitas o que achou?

**Comment by EsioFreitas** [comment]
Muito bom @gabrielalbino ! Bota dentro do drive renomeado.
