### ISSUE TITLE
Diagrama de argumentação das funcionalidades que estão dentro do escopo 

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#17]
# Issue Template

## Descrição da Issue
Fazer um diagrama que mostra porque escolhemos certas funcionalidades para o escopo do projeto.

## Funcionalidades

- [x] Tarefas;
- [x] Inventário;
- [x]  Lojas;
- [x] Grupo;
- [x] Desafios.

**Comment by Phe0** [comment]
coloca aqui quais as funcionalidades @EsioFreitas

**Comment by EsioFreitas** [comment]
Pronto

**Comment by rogerioo** [comment]
@EsioFreitas Eu acredito que grupos e times sejam a mesma coisa.

**Comment by rogerioo** [comment]
@EsioFreitas pensei nesses argumentos, o que acha?

# Argumentação

* **Ésio**: Precisamos definir o escopo de atuação do time para a aplicação
* **Pedro**: Tarefas é a principal
* **Saleh**: Temos que colocar o inventário também
* **Youssef**: A loja tem muitas funcionalidades
* **Lucas**: Não precisamos colocar a loja, vai ficar muita coisa
* **Rogério**: Mas sem a loja não faz sentido inventário, o usuário precisa de um lugar para comprar os items
* **Gabriel**: Sem items para personalizar o avatar, o mesmo perde o sentido
* **Ésio**: Acho os desafios bem importantes também, porque é uma motivação para o usuário
* **Lucas**: Não é tão complicado, podemos adicionar também
* **Youssef**: Vamos ficar com essas 4 funcionalidades então
* **Rogério**: Os grupos não são tão grandes, podemos incluir
* **Saleh**: É uma funcionalidade essêncial do processo de gamificação da aplicação
* **Gabriel**: Podemos fazer a taverna também
* **Pedro**: Com mais essa ficaremos sobrecarregados, ela é muito grande e os outros vão demandar muito, vamos fechar só nas 5 funcionalidade já discutidas

**Comment by gabrielalbino** [comment]
> @EsioFreitas Eu acredito que grupos e times sejam a mesma coisa.

@EsioFreitas Essa funcionalidade tá tanto na argumentação dos que entram no escopo quanto na que não entra, como faz?

**Comment by EsioFreitas** [comment]
@gabrielalbino , tem uma parte que eh beta. Bota ela

**Comment by EsioFreitas** [comment]
@rogerioo , ficou muito bom

**Comment by rogerioo** [comment]
V 1.0

![Untitled Diagram](https://user-images.githubusercontent.com/42387946/55293746-232d8700-53d0-11e9-8ba3-b92b4bec081c.png)

**Comment by rogerioo** [comment]
@EsioFreitas é assim mesmo?

**Comment by EsioFreitas** [comment]
Nossa, muito bom @rogerioo !!!
