### ISSUE TITLE
Montar Rich Picture da funcionalidade: Inventário

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#18]
# Issue Template

## Descrição da Issue
Montar RP da funcionalidade de inventario do aplicatiivo. 
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

**Comment by rogerioo** [comment]
V 1.0
![RP_Invetory_V1_1](https://user-images.githubusercontent.com/42387946/55284567-fdf93400-534f-11e9-831f-16112984258a.jpg)

**Comment by rogerioo** [comment]
Aguardo opinião do time para possíveis alterações

**Comment by Phe0** [comment]
@rogerioo no centro tem um baú q representa o inventário e ele aponta pra uma espada, q está dizendo ser inventário tmb. É pra ser assim msm?

**Comment by Phe0** [comment]
vou tentar desenhar ícones pra esse rich picture ainda hj

**Comment by Phe0** [comment]
Sem fundo
![Group 4](https://user-images.githubusercontent.com/31973465/55291241-ca9bc100-53b2-11e9-83b9-01e885b0cfe4.png)

Com fundo
![Group 5](https://user-images.githubusercontent.com/31973465/55291242-d4bdbf80-53b2-11e9-8b6d-9477c49a4cc9.png)

**Comment by rogerioo** [comment]
> @rogerioo no centro tem um baú q representa o inventário e ele aponta pra uma espada, q está dizendo ser inventário tmb. É pra ser assim msm?

@Phe0 Na verdade a espada é dos "itens", foi errado.

**Comment by rogerioo** [comment]
@Phe0 tem como você arrumar na versão digital, o nome do da armadura que é "equipamento"? Eu coloquei os mesmo nomes dos menus da app. E ficou faltando as setinhas do baú pra armadura e do baú para a espada escrito "possui".

**Comment by Phe0** [comment]
**Correção** 
**V 2.0**

Sem fundo
![Group 4 (1)](https://user-images.githubusercontent.com/31973465/55291813-b7402400-53b9-11e9-98b6-d3b609394514.png)

Com fundo
![Group 5 (1)](https://user-images.githubusercontent.com/31973465/55291822-be673200-53b9-11e9-82c7-67f5cd01f3e8.png)

**Comment by rogerioo** [comment]
Ficou show @Phe0, issue done!
