### ISSUE TITLE
Montar Rich Picture da funcionalidade: Lojas

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#19]
# Issue Template

## Descrição da Issue
Montar RP da funcionalidade de loja do aplicatiivo. 
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

**Comment by lucasdutraf** [comment]
v1.0 pronta, galera! Esperando feedbacks!
![rploja](https://user-images.githubusercontent.com/31940073/55293409-ba90db00-53cc-11e9-89ca-22b208744a83.jpg)

**Comment by rogerioo** [comment]
Ficou excelente @lucasdutraf!

**Comment by EsioFreitas** [comment]
Muito Bom!
