### ISSUE TITLE
Montar Rich Picture da funcionalidade: Contribuindo

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#20]
# Issue Template

## Descrição da Issue
Montar RP do guia de contribuição do habitica
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

link: https://habitica.fandom.com/wiki/Contributing_to_Habitica

**Comment by lucasdutraf** [comment]
Galera! Segue v1.0 do Rich Picture sobre o contribuindo do habitica
![rpcontribuindo](https://user-images.githubusercontent.com/31940073/55298205-c3040880-5402-11e9-834e-dbc791f121cb.jpg)

**Comment by rogerioo** [comment]
Ficou show @lucasdutraf!
