### ISSUE TITLE
Montar Rich Picture da funcionalidade: Grupo

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#21]
# Issue Template

## Descrição da Issue
Montar RP da funcionalidade de grupo do aplicatiivo. 
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

**Comment by devsalula** [comment]
v1 RP Grupos
![RPGrupos](https://user-images.githubusercontent.com/35435199/55294824-dd2af000-53dc-11e9-92c6-d0966ad2cc0a.jpg)

**Comment by EsioFreitas** [comment]
Esta otimo @devsalula
