### ISSUE TITLE
Montar Rich Picture da funcionalidade: Desafios

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#22]
# Issue Template

## Descrição da Issue
Montar RP da funcionalidade de desafios do aplicatiivo. 
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

**Comment by lucasdutraf** [comment]
Essa issue vai ser terminada?

**Comment by kaiquebuilds** [comment]
O RP foi feito e já está no Drive!

**Comment by lucasdutraf** [comment]
@kaiqueborges comenta aqui a imagem dele! Para mantermos o rastro com data e tudo mais.

**Comment by kaiquebuilds** [comment]
![RPDesafiosV1](https://user-images.githubusercontent.com/14828276/55677624-b891b500-58c1-11e9-8f6e-4dd1dfe5f023.jpeg)

Lembrando que será atualizado e melhorado!
