### ISSUE TITLE
Montar Rich Picture da funcionalidade: Tarefas

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#23]
# Issue Template

## Descrição da Issue
Montar Rich Picture da funcionalidade de tarefas do aplicatiivo. 
OBS.: não esqueça de ter bastante fluxo e não construir um mapa mental

**Comment by Phe0** [comment]
oq é RP, é melhor escrever por extenso ou colocar uma legenda

**Comment by EsioFreitas** [comment]
Ok. Vou alterar

**Comment by gabrielalbino** [comment]
@EsioFreitas 
![A4](https://user-images.githubusercontent.com/31973465/55296972-2b4ced00-53f7-11e9-8888-c24b26a8cf1f.png)

(https://www.figma.com/file/cs65ewuXx2MktYE4qsFTIVQq/RichPicture-Tarefas?node-id=0%3A1)

**Comment by rogerioo** [comment]
Rich picture finalizado e revisado.
