### ISSUE TITLE
Escrever texto "Sobre a Disciplina"

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#24]
# Issue Template

## Descrição da Issue
Escrever texto falando sobre a disciplina para ser colocado na wiki

**Comment by Phe0** [comment]
Texto terminado 
https://docs.google.com/document/d/1txFCXlFIuv-31Ndkq1wKqB9n1yykIDgb9wTqFLV6R8M/edit

**Comment by EsioFreitas** [comment]
Ficou muito bom @Phe0

**Comment by rogerioo** [comment]
Ficou excelente @Phe0 !
