### ISSUE TITLE
Escrever texto "Sobre o Habitica"

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#25]
## Descrição da Issue
Escrever texto sobre o app Habitica para ser colocado na wiki

**Comment by Phe0** [comment]
Texto disponível em:
https://docs.google.com/document/d/1jmBWR5xDh9AdlSPvEx1VxzUG8z598j6ivwJTFjkpe9A/edit

**Comment by EsioFreitas** [comment]
Muito bom @Phe0
