### ISSUE TITLE
Elaborar Rich Picture - Individualmente

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#3]
## Descrição da Issue
Foi acordado em grupo após a aula do dia 25/03/2019 que cada integrante faria um Rich Picture de sua escolha baseado na aplicação que teremos como base na matéria.

### Tasks:
- [x] @youssef-md 
- [x] @gabrielalbino 
- [x] @lucasdutraf 
- [x] @Phe0 
- [x] @devsalula  
- [x] @rogerioo 
- [x] @EsioFreitas

**Comment by lucasdutraf** [comment]
Galera, a medida que forem acabando seus Rich Pictures marquem o check box da issue e mandem nos comentários da issue também!

**Comment by rogerioo** [comment]
Pode pá!

**Comment by lucasdutraf** [comment]
Apenas lembrando, a deadline é até terça 26/03 à noite, pois nesse turno nos reuniremos para montarmos nossa Rich Picture em grupo!!

**Comment by rogerioo** [comment]
Mas o artefato do grupo não vai ser feito em sala durante a dinâmica?

**Comment by lucasdutraf** [comment]
> Mas o artefato do grupo não vai ser feito em sala durante a dinâmica?

Não sei! Interpretei que teríamos que chegar com o artefato geral já pronto

**Comment by rogerioo** [comment]
> Não sei! Interpretei que teríamos que chegar com o artefato geral já pronto

Boa questão! Acredito que com os artefatos individuais prontos fica mais fácil para fazer o do grupo e podíamos aproveitar o tempo da dinâmica. Mas vemos durante o dia quando o grupo estiver disponível!

**Comment by gabrielalbino** [comment]
O que acham de colocarmos os rich picture aqui nos comentários na medida em que ficarem prontos pra gente dar uma olhada antes de nos reunirmos?

**Comment by gabrielalbino** [comment]
![Untitled Diagram (1)](https://user-images.githubusercontent.com/30835149/55024054-d5cea580-4fdc-11e9-8446-e3f07b3bb54a.png)

**Comment by Phe0** [comment]
V1
![photo4963125286996650064](https://user-images.githubusercontent.com/31973465/55160996-50193a00-5143-11e9-8277-23fc8d43eaec.jpg)

V2
![photo4958980935613786126](https://user-images.githubusercontent.com/31973465/55041594-7e482e00-500c-11e9-85c9-dc41e7f25166.jpg)

**Comment by EsioFreitas** [comment]
![photo_2019-03-26_21-24-08](https://user-images.githubusercontent.com/34384624/55042212-4393c500-500f-11e9-8823-76668546aedb.jpg)

**Comment by EsioFreitas** [comment]
![photo_2019-03-26_21-24-08](https://user-images.githubusercontent.com/34384624/55042240-658d4780-500f-11e9-9e6e-77bc4e225b98.jpg)

**Comment by lucasdutraf** [comment]
![photo_2019-03-26_21-40-08](https://user-images.githubusercontent.com/31940073/55042361-dfbdcc00-500f-11e9-8c67-9048c3a7c1fa.jpg)

**Comment by EsioFreitas** [comment]
![photo_2019-03-26_21-24-08](https://user-images.githubusercontent.com/34384624/55042422-24e1fe00-5010-11e9-807f-0e99fa047b50.jpg)

**Comment by gabrielalbino** [comment]
v2
![Untitled Diagram (3)](https://user-images.githubusercontent.com/30835149/55043373-c2d7c780-5014-11e9-84e7-9599581795ec.png)

**Comment by devsalula** [comment]
v1 - Saleh
![RichPictureSaleh](https://user-images.githubusercontent.com/35435199/55047181-9dea5100-5022-11e9-9935-c860905bd3ae.jpg)

**Comment by rogerioo** [comment]
V1

![RP_V1_1](https://user-images.githubusercontent.com/42387946/55048035-7ba60280-5025-11e9-8abd-fffa870897d0.jpg)

**Comment by youssef-md** [comment]
![photo4963046813649184783](https://user-images.githubusercontent.com/29265857/55104239-c6b52980-50a8-11e9-96d2-215a7d20c726.jpg)
