### ISSUE TITLE
Insides para reunião 04/05 

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#32]
# Issue Template

## Descrição da Issue
Documento com insides que os mebros tiveram sobre a etapa de elicitação.

**Comment by EsioFreitas** [comment]
https://www.evernote.com/shard/s596/sh/8225c3d2-ad9d-4c92-aa4b-d63095e24bda/780443636f0fe9898ad895ac46e6b2a6

**Comment by gabrielalbino** [comment]
Galera, aqui vai minhas ideias:
Brainstorm:
Podiamos bolar um dialogo da galera pensando em como colocariam gamificação pra incentivar os usuários a utilizarem os apps (classes, itens exclusivos de classe, recompensas, loja, archivments (que a gente deixou de fora até agora e existe no app), etc)
Storytelling e prototipação: podiamos juntar as duas e fazer um story telling de prototipação, tipo contar o modo da evolução da interface (com prototipos) a medida em que realizaram-se testes com diferentes usuários (meio viajado mas achei ousado e acho que eles gostariam de ver as tecnicas sendo usada em conjunto)
Entrevista: Montar um roteiro com perguntas de como a pessoa organiza suas tarefas diárias para conseguir levantar os requisitos funcionais que geraram os itens "to-do list, daily e habits)
Não sei se convém falar isso também, mas achei que a etnegrafia tem um grande potencial, só n sei como explora-la, mas sinto que será pouco explorado pelos outros grupos e a gente podia mostrar ela tb (só falta decidir como e se vale a pena)

**Comment by rogerioo** [comment]
# Decisões da reunião

## Artefatos para Pré-Entrega
* Criar logo do Habitica com palavras de funcionalidade que o compõe (brainstorming)
* 5W2H
* Documento de visão versão simplificada
* Questionário
* Glossário 
* Storytelling
* Requisitos funcionais e não funcionais (individuais de acordo com os Rich Pictures)
* Mais ideias a serem propostas posteriormente

## Wiki
* Usar React ao invés do Docussaurus para manter a Wiki

**Comment by lucasdutraf** [comment]
# Decisões Pré-Orientação
* Fazer um questionário para jogar dentro dos fóruns do Habitica. Dutra + Youssef
* Terminar o Documento de Visão. Ésio + Albino 
* Priorização QFD + complexo. SaFEo
* Priorização First Things. Kaique + Rogerio
* Priorização ROI. Kaique + Rogerio
* Transformar o RP de gamificação em requisitos não funcionais. SaFeo
* Juntar todos os RNF e RF e adicionar gamificação e privacidade. Lucas + Youssef 
* Priorização MoSCoW. Ésio + Albino

# Apresentação
* Requisitos de alto nivel - 5W2H
* RF
* RNF
* Priorização

**Comment by rogerioo** [comment]
# Decisões Pós-Orientação
* FTF e Moscow -> Gabriel
* Etnografia -> Féo
* Storytelling -> Ésio
* Questionario -> Lucas
* Analise do  Discurso -> Kaique
* Youssef -> Brainstorming
* Saleh - Entrevista
* Rogerio - QFD
