### ISSUE TITLE
Brainstorming sobre o que representa o Habitica

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#33]
# Issue Template

## Descrição da Issue
O time deve se reunir para fazer um brainstorming sobre palavras que representa o Habitica. A entrega deve ser uma imagem com a logo do Habitica feito com as palavras

**Comment by lucasdutraf** [comment]
Para cumprimento da issue seria ideal nos reunirmos, de preferência pessoalmente.

**Comment by EsioFreitas** [comment]
Para gente mostrar isso segunda, não tem como ser pessoalmente. Acho que poderiamos até fazer pelo telegram mesmo.

**Comment by lucasdutraf** [comment]
Vamos fazer hoje após a dinâmica?! @requisitos-habitica/requisitos-habitica

**Comment by lucasdutraf** [comment]
# BRAINSTORM HABITICA
Habitos
Tarefa
organização
gamificação 
avatar
missão
atividade
transformação
engajamento
RPG
comunidade 
mascote
evolução
motivação
hacker
personagem
desafios
espada
armadura
dragão
moedas
trabalho em equipe
chefão
gatuno
mago
guerreiro
curandeiro
premios
feedback
priorização
white hat
monstro
grupo
desafios
armadura
guilda
flor
compras
chat
experiência
pet
vida
itens
capacete

**Comment by Phe0** [comment]
![Group 9 (2)](https://user-images.githubusercontent.com/31973465/55806633-06234300-5ab7-11e9-9f83-030ea6e2082b.png)

**Comment by youssef-md** [comment]
Como decidimos refazer o Brainstorm após a conversa com o Maurício e com a dica do @EsioFreitas eu fiz um Brainstorm com 3 pessoas que não conheciam o Habitica sobre funcionalidades que elas acham interessantes, dado os tópicos que levantei.

Participantes: Alice Cavalcante, Ana Beatriz, Paulo Henrique

### Como transformar o processo de planejamento de afazeres e contrução de hábitos em algo prático e menos desinteressante ?

- **Paulo**: Planejando com um grupo de pessoas com interesses parecidos.
- **Ana:** Tem que ser alguma coisa que você consiga ver todos os dias e que te motive a continuar até que você consiga criar um hábito, porque para formar um hábito é uma tarefa cansativa, e se não sentir uma evolução do estado em que estava você se desmotiva.
- **Alice**: Para deixar prático eu penso em integrar com a tecnologia, pode ser algum site ou um aplicativo mesmo já que todo mundo anda com celular, fica mais fácil para lembrar que voce fez alguma tarefa que planejou.
- **Paulo:** Então dá pra juntar o que elas disseram, o grupo ele ajuda na parte de manter as pessoas motivadas, porque todos vão estar juntos nessa tarefa, então caso uma pessoa não esteja tão motivada, ela pode enxergar no grupo uma motivação, coisa que ela não veria se estivesse sozinha. E um aplicativo ou site facilita nessa outra parte de praticidade, se estiver no celular da pessoa as tarefas dela, e os hábitos que ela quer formar, durante o dia ela vai conferindo se esta perto de completar algo, e se motivar a ir completar.
- **Alice:** Dependendo do hábito, vai ser bem difícil de manter a pessoa motivada se ela não ver uma evolução para se sentir satisfeita com o andamento, por isso muita gente desiste de academia, porque além de fazer o esforço, a parte boa que são os resultados dos treinos demoram a surgir. Então se é pra pessoa se sentir motivada a continuar persistindo eu acho necessário algum mecanismo que a deixe melhor ao completar sua meta.

### Trazer elementos dos jogos para a ferramenta deixaria o usuário mais engajado?

- **Ana:** Vai depender do público, hoje em dia todo mundo gosta de jogar, então pegar algumas coisas que sejam comuns nos jogos vai deixar mais interessante, porque tira um pouco o foco do esforço necessário das tarefas trazendo uma descontração.
- **Paulo:** Como a Alice disse da preocupação com a motivação do usuário e que pra ele continuar persistindo em algo que ele deve fazer era legal que tivesse algo que o deixasse melhor ao completá-la, os jogos são perfeitos pra isso porque eles tem vários mecanismos de prender o jogador para que ele invista o tempo dele, então se conseguir mudar o contexto desse investimento do tempo e ao inves de ser em jogo ele focar nas tarefas dele seria perfeito.
- **Alice:** Seria perfeito mesmo, tipo quando ele completar uma parte de um hábito dele, por exemplo ele quer parar de fumar então a cada hora que ele ficar sem fumar ele ganhasse uma recompensa, faria com que ele se sentisse melhor e motivaria a ele repetir essa ação boa que deu uma recompensa a ele.
- **Ana:** Mas a pessoa tem que ganhar esses dinheiros dos jogos, ela tem que poder gastar com algo, porque assim faz com que ela perca essa recompensa e seja forçada a ganhar mais, e tem que ter coisas para ela gastar que sejam cada vez melhores pra ficar nesse ciclo de ser recompensada e querer comprar.
- **Paulo:** Assim como nos jogos tem fases que são mais difíceis que outras, pode ser legal isso também, que tenham tarefas mais difíceis que outras e por isso recompensariam mais
- **Alice:** Até agora ele só ganha recompensa e gasta essas recompensas, ele só pederia comprando alguma coisa, e os jogos são desafiadores pra manter a pessoa semṕre querendo passar de fase. Como a pessoa vai colocar um monte de tarefas que ela quer fazer seria bom que essas tarefas que ela deixasse de fazer depois do prazo dela, que o não cumprimento dessa tarefa prejudicasse ele, porque assim ele vai querer sempre completar tarefas pra ganhar, e sabe que se deixar de fazer ele vai ser prejudicado, assim ele vai se planejar melhor em quais tarefas ele quer realizar, e não só jogar um monte.
- **Ana:** Tem que estar claro tudo isso pra pessoa que vai usar, porque o foco é que ela consiga se planejar melhor, separando o que ela tem pra fazer, se ela quer formar algum hábito ou fazer suas tarefas diárias para criar uma rotina nova pra si. Porque tem varias coisas pode confundir ele ou tirar o foco da proposta inicial.

**Comment by youssef-md** [comment]
Com isso irei elicitar os requisitos presentes neste Brainstorm

**Comment by rogerioo** [comment]
Artefato confeccionado e entregue.
