### ISSUE TITLE
Fazer 5W2H

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#34]
# Issue Template

## Descrição da Issue
Cada membro deve fazer 5W2H do Habitica para poder conhecer melhor o domínio que ele se encontra.

- [x] @youssef-md 
- [x] @gabrielalbino 
- [x] @lucasdutraf 
- [x] @Phe0 
- [x] @devsalula  
- [x] @rogerioo 
- [x] @EsioFreitas  
- [x] @kaiqueborges

**Comment by gabrielalbino** [comment]
Vou colocar aqui, espero não influenciar ninguém
**Não leia antes de fazer o seu caso tenha medo de ser influenciado e o seu for ficar igual** hehehe

# 5W2H

## WHAT

Gerenciamento de afazeres dos usuários de modo a incentivar o uso do app.

## WHY

* Falta de aplicativos gamificados de maneira eficiente para manter os usuários interessados em continuar usando a aplicação
* Possibilidade de lucrar coma gamificação através da compra de elementos do jogo

## WHERE

O usuário poderá gerenciar suas atividades em qualquer lugar utilizando o smartphone

## WHEN

O gerenciamento de tarefas poderá ser feito 
de qualquer lugar utilizando o smartphone

## WHO

_Não sei como aplicar essa questão_

## HOW
 
Pela utilização de um aplicativo ou site onde o gerenciamento será feito em busca de recompensas

## HOW MUCH?

_Não sei como aplicar essa questão_

**Comment by Phe0** [comment]
# 5W2H

## WHAT
App para criação de hábitos e gerenciamento de atividades gamificado

## WHY
Para que pessoas possam se sentir mais motivadas ao realizar suas tarefas, tendo uma sensação de feedback instantâneo ao completar algo

## WHERE
Qualquer lugar com acesso ao website ou ao app

## WHEN
Qual momento desde que tenha acesso ao website ou ao app

## WHO
Os usuários são pessoas que pretendem organizar melhor as atividades e hábitos do seu dia-a-dia afim de ter uma melhor gestão de tempo ou gratificação por realizar tarefas

## HOW
 Através de um app ou site que utilizam técnicas de gamificação

**Comment by EsioFreitas** [comment]
# 5W2H

## WHAT
Uma aplicação para poder gerenciar obrigações (hábitos, atividades diárias e afazeres) de uma forma lúdica.
## WHY
Pois as pessoas tem obrigações e precisam ter uma ferramenta que ajudem gerenciar elas de uma forma mais efetiva.
## WHERE
Em qualquer lugar com acesso a plataforma.
## WHEN
Em qualquer momento se estiver com a plataforma
## WHO
Pessoas que precisam organizar suas obrigações e que acham isso cansativo ou chato.
## HOW
Por meio de uma plataforma gamificada, Habitica.

**Comment by lucasdutraf** [comment]
# 5W2H
## WHAT
Aplicação de gerenciamento de atividades de forma gamificada.
## WHY
Existem muitas ferramentas de gerência de atividades, porém o usuário não se sente incentivado a continuar usando a ferramenta e acaba abandonando. O gerenciamento de atividades gamificado ajuda a combater a monotonia e a falta de necessidade de voltar a usar a aplicação, envolvendo o usuário no mundo de Habitica, o que faz o app ser mais atrativo para, principalmente, o público jovem.
## WHERE
Habitica.
## WHEN
Quando surgir a necessidade de gerenciar tarefas e controlar hábitos.
## WHO
Principalmente o público jovem, porém é aberto para pessoas de todas as idades.
## HOW
O aplicativo dispõe de uma série de técnicas de gamificação, permitindo seu usuário a ser representado por um avatar, contendo prêmios ao concluir tarefas ou eliminando maus hábitos, mas também prejudicando o usuário ao executar maus hábitos. Isso leva ao envolvimento com a aplicação, para tornar seu avatar cada vez mais forte, que também acarreta no bom planejamento e organização da pessoa que está por trás disso.
## HOW MUCH
É gratuito para usuários comuns, porém possui assinaturas que liberam mais conquistas para o usuário, custando de R$5,00 a R$48,00 ao ano.

**Comment by devsalula** [comment]
# 5W2H

## WHAT
Aplicativo para gerenciar atividades diárias, atividades pontuais e hábitos (sejam bons ou ruins), ajudando os seus usuário a enxergar as suas tarefas de maneira mais interativa. 

## WHY
Porque em um mundo onde tarefas e atividades se tornam cada vez mais complexas, as pessoas necessitam de uma ferramenta atrativa, para que possam melhorar a sua gestão de atividades.

## WHERE
No aplicativo do Habitica ou em seu site.

## WHEN
A qualquer momento do seu dia.

## WHO
Pessoas que possuem uma grande quantidade de afazeres, mas que não se sentem atraídas por outras aplicações não lúdicas. 

## HOW
A partir do aplicativo ou site do Habitica, utilizando das suas técnicas de gamificação para ficar mais interessante para seus usuários.

## How Much?
É gratuito para qualquer pessoa.

**Comment by youssef-md** [comment]
# 5W2H

## WHAT
Software para facilitar a visualização e a realização tarefas rotineiras e/ou atividades com os mais diversos intuitos.
## WHY
Por que ao listar as atividades que temos que fazer nós não só nos planejamos melhor, como também o nosso subconsciente já vai trabalhando em como realizá-las, aumentando assim a chance de cumprí-las. 

## WHERE
Em qualquer software com acesso a aplicação web ou em qualquer smartphone pelo aplicativo.

## WHEN
Quando quiser, seja para cumprir uma tarefa ou para checar o seu andamento.

## WHO
Pessoas que querem adquirir um hábito de forma que motive esta árdua caminhada.

## HOW
Recompensando aqueles que cumprem suas tarefas, com experiência e com várias moedas a depender do que foi feito, para que o usuário evolua seu avatar, motivando ela a continuar realizando seus afazeres.

## How Much?
Gratuito para qualquer pessoa.

**Comment by kaiquebuilds** [comment]
# 5W2H

## WHAT

Uma aplicação de produtividade gamificada para organizar coisas a fazer.

##  WHY

Porque não existe um app de produtividade gamificado e isso ajudaria a engajar de fato nas tarefas.

## WHERE

Em um app mobile ou no browser.

## WHEN

Quando quiser guardar coisas a fazer.

## WHO

Um time central, mas com o código aberto, desenvolvedores do mundo inteiro.	

## HOW 

Usando técnicas de gamificação para aumentar o apelo do app.

## HOW MUCH

A maior parte da aplicação será gratuita, com alguns extras mediante assinatura paga.

**Comment by rogerioo** [comment]
# 5W2H

## WHAT

Uma aplicação de gerenciamento de tarefas que auxilie seus usuários a realizar sua organização pessoal de forma eficiente e lúdica com o uso de ferramentas gamificadas

## WHY

Organização gera produtividade e bem estar àqueles que realizam seu gerenciamento, e o uso da gamificação pode ser uma motivação para esse planejamento.

## WHERE

Uma aplicação mobile, pois permite o gerenciamento em tempo real das tarefas, tanto em inserção e acompanhamento das atividades diárias, e uma aplicação Web para permitir melhor integração entre as pataforma de acordo com o que for melhor ao usuário

## WHEN

Campanha de arrecadamento inicia em Janeiro de 2013 e a corporação criada pelos fundadores começa em 2014.

## WHO

Tyler Renelle, Siena Leslie e Vicky Hsu

## HOW

Aplicação Web em Javascript, Android Nativo em Kotlin e IOS Nativo em Swift.

## HOW MUCH?

Para desenvolvimento inicial do projeto, foram realizadas doações pelo site *Kickstarter*, que arrecadou um total de $41,191

***
**Referências**

Wikipedia contributors. **Habitica**. Wikipedia, The Free Encyclopedia. Disponível em: <https://en.wikipedia.org/wiki/Habitica#cite_note-17>. Acesso em: 07/04/2019

Kickstater of Habitica from January 10, 2013 to February 19, 2013. Disponível em: <https://www.kickstarter.com/projects/lefnire/habitrpg-mobile>. Acesso em: 07/04/2019

Repositório Oficial da Organização do Habitica. Disponível em: <https://github.com/HabitRPG>
