### ISSUE TITLE
Documento de visão versão simplificada

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#35]
# Issue Template

## Descrição da Issue
Fazer documento de visão versão simplificada como entrega do elicitação de requisitos de alto nível.

**Comment by EsioFreitas** [comment]
Add o doc no drive. Quem quiser alterando, pode começar. Não esqueça de preencher a parte de revisão

https://docs.google.com/document/d/1BQhbtSGft7ZBOn6A8M9Z7wrN13IkrgCGNnWVExrUATI/edit?usp=sharing

**Comment by lucasdutraf** [comment]
Galera, eu e o @EsioFreitas estamos comentando algumas coisas no doc de visão e seria interessante a opinião de todos! @requisitos-habitica/requisitos-habitica

**Comment by rogerioo** [comment]
Já escrevi a introdução lá, quem puder revisar eu agradeço!
