### ISSUE TITLE
Elaborar questionário

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#36]
## Descrição da Issue
Conforme acordado na reunião, após reunirmos informações sobre o público alvo do Habitica, elaboraremos um questionário que será divulgado nas comunidades das redes sociais onde fizer mais sentido ele estar.

**Comment by rogerioo** [comment]
[Questionário](https://docs.google.com/forms/d/e/1FAIpQLSdd93tgzt3IGulhBadpKgLSYKnWpzF_vrF1CwdGjgX4ITeMsQ/viewform?usp=sf_link) disponível e rodando.
