### ISSUE TITLE
Criar glossário do app

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#37]
## Descrição da Issue
Foi acordado que levantaremos uma série de palavras que pertencem ao mundo do Habitica.

**Comment by lucasdutraf** [comment]
# Glossário do App

* **Guilda** - Guildas são grupos sociais criados por outros jogadores que podem oferecer ajuda, encorajamento e responsabilidade mútua.
* **Taverna** - Chat para a comunidade do Habitica se comunicar.
* **Poções** - Item que causa algum efeito ao avatar, podendo conceder mais vida ou alguma ação especial no app.
  * **Poções de Eclosão** - Poção que é usada para chocar ovos de mascotes.
* **Loja Sazonal** - Loja do aplicativo que muda de acordo com as estações, contendo itens especiais para cada uma.
* **Ampulheta mística** - Moeda especial para assinantes do aplicativo, utilizada para comprar itens épicos.
* **Quest** - Tarefa especial que pode ser realizada em grupo ou individualmente, onde deve-se vencer um *Boss* causando dano ao realizar as tarefas, e ao derrotar o *boss* os participantes serão recompensados.

* **Boss** - Inimigo poderoso que aparece ao entrar em uma Quest.
* **Classes** - Tipo de "herói" que o seu avatar pode escolher ser:
  * **Guerreiro**:
    * Causa mais danos em *bosses* 
    * Maior chance de acertos críticos, sendo recompensado por isso
    * Defesa moderada contra dano
    * Pode dar *buff* *STR* e *CON* para o grupo
  * **Mago**:
    * Ganha experiência mais rápido
    * Pode dar *buff* *INT* para membros do grupo
    * Causa um dano adicional  em *bosses* e pode efetuar *freeze streaks*
  * **Curandeiro**:
    * Mais resistente a danos
    * Pode se curar
    * Pode dar *buff* *CON* nos membros do grupo recuperando suas vidas
  * **Gatuno**:
    * Acha a maioria dos *drops* e ouros
    * Maior chance de causar acertos críticos
    * Pode dar *buff* *PER* ao grupo
* **Buffs** - ferramenta que aumenta os status do avatar
* **Gemas** - Moeda utilizada no aplicativo para compra de itens especiais.
* **Ouro** - Moeda utilizada no aplicativo para compra de itens simples.

**Comment by lucasdutraf** [comment]
Galera, levantei essas palavras que são "especiais" do app, podem editar a medida que forem encontrando mais! 
Outra coisa, colocamos o significado na frente? @requisitos-habitica/requisitos-habitica

**Comment by EsioFreitas** [comment]
> Galera, levantei essas palavras que são "especiais" do app, podem editar a medida que forem encontrando mais!
> Outra coisa, colocamos o significado na frente? @requisitos-habitica/requisitos-habitica

Sim migo

**Comment by lucasdutraf** [comment]
Prontinho @EsioFreitas

**Comment by lucasdutraf** [comment]
@requisitos-habitica/requisitos-habitica movi a issue para review, mas podem adicionar e corrigir o que já está no comentário acima!

**Comment by youssef-md** [comment]
Adicionei: quest, boss e as classes que podem ser escolhidas, se alguma coisa na definição não estiver legal, sintam-se avontade para corrigir.
Obs.: o que está em itálico foi porque não achei um tradução que ficasse bom ou porque falta definí-la no glossário

**Comment by lucasdutraf** [comment]
> Adicionei: quest, boss e as classes que podem ser escolhidas, se alguma coisa na definição não estiver legal, sintam-se avontade para corrigir.
> Obs.: o que está em itálico foi porque não achei um tradução que ficasse bom ou porque falta definí-la no glossário

Top! Só mudei o nome das classes para PT-BR :smiley_cat:
