### ISSUE TITLE
Storytelling Habitica

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#38]
## Descrição da Issue
O produto dessa issue será um storyboard de "caso de uso" do Habitica, ou seja, qual situação leva o usuário a fazer o uso do app.

**Comment by Phe0** [comment]
Artigo legal mostrando os impactos do storytelling na elicitação de requisitos 
https://ieeexplore.ieee.org/document/6043945

**Comment by Phe0** [comment]
Link para se basear ao estruturar storytellings, são histórias reais de usuários 
https://habitica.wordpress.com/category/use-case-spotlight/

**Comment by EsioFreitas** [comment]
Exemplo de storytelling e as funcionalidades retiradas 

https://requisitos-2018-2.github.io/airbnb/elicitacao/index.html

**Comment by EsioFreitas** [comment]
@Phe0  e @youssef-md , temos 5 features e cada uma delas os outros vao fazzer os requisitos funcionais e nao funcionais. Que tal cada um de nós fazer um storytelling com essa features. Por exemplo, eu fiz com atividades e grupos. E nisso o proximo faz com mais dois diferentes e o proximo com um e mais outro. Pode repeti, mas seria legal a gente poder abranger as 5 features. Além disso, acho legal a gente esperar os menino fazerem os requisitos para a gente pegar aquele de acordo com a nossa historia para poder manter um padrao.

**Comment by EsioFreitas** [comment]
## Reorganizando minhas obrigações 
Certo dia, decidi criar o hábito de me alongar pela manhã. No entanto, sempre me esquecia dessa atividade, pois não estava acostumado. Por isso adicionei no meu aplicativo de gerenciar atividades esse meu novo hábito. Depois de perceber o benefício dessa prática, decidi criar novos hábitos, tais como: comer a cada 3 horas, tomar 2 litros de água por dia, meditar. Mas chegou uma hora que meus novos hábitos e minhas tarefas começaram a ficar misturadas e isso começou a me incomodar. 
	Depois de falar a minha situação para um amigo, ele me indicou um novo aplicativo chamado Habitica. Nele eu poderia separar minhas tarefas dos meus novo hábitos. Além disso, nele eu posso ter uma área apenas para as minhas atividades diárias. Outra vantagem é poder colocar etiquetas nas minhas obrigações e poder buscá-las por atividades feitas, por etiqueta e por data.
Outro ponto interessante é poder registrar atividades com outras pessoas. Pude assim criar um grupo com a minha família para podermos dividir nossas obrigações uns com os outros, como compras, dia de pagar contas e marcar eventos familiares. Nessa parte da aplicação, podemos conversar sobre as origações, fazer desafios juntos e reagir a comentarios uns dos outros.
 Por fim, gostei muito, pois agora tenho um aplicativo que posso deixar minha obrigações mais organizadas e me interagir com meus familiares de uma forma interativa em relação as nossas atividades compartilhadas. 

### Requisitos atividades 
* O usuario deve se capaz de adicionar atividades diárias.
* O usuario deve se capaz de adicionar habitos.
* O usuario deve se capaz de adicionar afazeres.
* O usuario deve poder criar etiquetas.
* O usuario deve poder editar.
* O usuario deve poder excluir etiquetas.
* O usuario deve poder fazer busca de obrigações por etiqueta.
* O usuario deve poder fazer busca de obrigações por nome.
* O usuario deve poder fazer busca de obrigações por data.
* O usuario deve poder editar dados das obrigações.

### Requisitos grupo 
* O usuario deve poder criar um grupo.
* O usuario deve poder adicionar outros usuarios ao grupo.
* O usuario deve poder retirar outros usuarios do grupo.
* O usuario deve poder sair do grupo.
* O usuario deve poder se comunicar com outros usuarios do grupo.
* O usuario deve poder reagir aos comentário de outros usuarios do grupo.
* O usuario deve poder participar de desafios com os usuarios do grupo.
* O usuario deve poder sair do desafio.
* O usuario deve poder editar dados do grupo.

**Comment by Phe0** [comment]
> @Phe0 e @youssef-md , temos 5 features e cada uma delas os outros vao fazzer os requisitos funcionais e nao funcionais. Que tal cada um de nós fazer um storytelling com essa features. Por exemplo, eu fiz com atividades e grupos. E nisso o proximo faz com mais dois diferentes e o proximo com um e mais outro. Pode repeti, mas seria legal a gente poder abranger as 5 features. Além disso, acho legal a gente esperar os menino fazerem os requisitos para a gente pegar aquele de acordo com a nossa historia para poder manter um padrao.

Não vejo pq esperar os outros, estamos usando a técnica para levantar requisitos, quanto mais visões diferentes tivermos melhor, mas podemos sim usar as features como base

**Comment by youssef-md** [comment]
Concordo com o @phe0 podemos usar as features que já estão divididas para dar um escopo ao storytelling, mas vamos fazer uma v1 antes deles entregarem os requisitos e uma v2 após, para que nós possamos comparar diferentes pontos de vista, vai que nisso novos requisitos surgem

**Comment by EsioFreitas** [comment]
Coloquei os requistos. Nisso o meu não abange a gamificação. Podiamos tratar a gamificação como uma feature separada. Nisso temos as features: inventario, loja, desafios e gamificação. O que acham?

**Comment by lucasdutraf** [comment]
Galera, além do storytelling também seria legal produzirmos um storyboard? Ou acham que vai ser overhead para essa entrega?

**Comment by Phe0** [comment]
> Galera, além do storytelling também seria legal produzirmos um storyboard? Ou acham que vai ser overhead para essa entrega?

Acho q vai ser um pouco de overhead, preferia trabalhar melhor em outras técnicas ou ir mais a fundo nas q escolhemos

**Comment by Phe0** [comment]
Estou usando histórias de usuários reais como base para retirar requisitos, segue o link do drive
https://docs.google.com/document/d/1SW8o1fRfsevq5We-oNvI1UIEqmMdHa1nINnHc8Ji-ko/edit

**Comment by lucasdutraf** [comment]
> > Galera, além do storytelling também seria legal produzirmos um storyboard? Ou acham que vai ser overhead para essa entrega?
> 
> Acho q vai ser um pouco de overhead, preferia trabalhar melhor em outras técnicas ou ir mais a fundo nas q escolhemos

Certo!

**Comment by EsioFreitas** [comment]
Galera, criei um doc com o storytelling 
https://docs.google.com/document/d/10EEshvIepg2VCQm77B_rgDyzeMAZJ8-F_1UWqbum9V0/edit#

**Comment by rogerioo** [comment]
Artefato confeccionado e entregue.
