### ISSUE TITLE
Requisitos funcionais e não funcionais

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#39]
## Descrição da Issue
O membro que for designado para o cumprimento da issue deve relacionar os requisitos funcionais e não funcionais da parte do app que previamente elaborou o Rich Picture

**OBS** Cada pessoa vai elicitar os requisitos da parte que fez o RP.

**Comment by lucasdutraf** [comment]
Galera, o que acham de separarmos essa issue em uma específica para cada parte?
@requisitos-habitica/requisitos-habitica

**Comment by EsioFreitas** [comment]
Acho uma boa. Nisso quem não for fazer essa issue, pois não dá para todo mundo, poderia fazer a do storytelling.
