### ISSUE TITLE
Elaborar Rich Picture - Individualmente

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#4]
## Descrição da Issue
Foi acordado em grupo após a aula do dia 25/03/2019 que após cada integrante fazer um Rich Picture de sua escolha baseado na aplicação, nos reuniremos para elaborar um com todas as visões do time.

**Comment by rogerioo** [comment]
Teste

**Comment by rogerioo** [comment]
teste

**Comment by youssef-md** [comment]
Segue a parte 1 do Rich Picture elaborado hoje na dinâmica de grupo 

![photo4960836486039709904](https://user-images.githubusercontent.com/29265857/55126287-5aa7e500-50eb-11e9-8bdf-baf2f43a112d.jpg)

**Comment by EsioFreitas** [comment]
Galera cade a parte 2?
