### ISSUE TITLE
Elicitar requisitos funcionais e não funcionais: Grupo

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#40]
# Issue Template

## Descrição da Issue
Elicitar requisitos funcionais e não funcionais da funcionalidade de Grupo

**Comment by devsalula** [comment]
Levantei alguns dos requisitos da parte dos grupos.
Mas ainda tenho um pouco de dificuldade com os requisitos não funcionais, principalmente porque não tenho ideia dos tempos de requisição do app.
**Se puderem dar feedback, ficarei grato.**

[Requisitos - Grupos](https://docs.google.com/document/d/1f9TqfCb5Vw1fLqWkyIQDfV2PnjeLnMYgt7jnoibZwkg/edit#)
