### ISSUE TITLE
Elicitar requisitos funcionais e não funcionais: Tarefas

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#41]
# Issue Template

## Descrição da Issue
Elicitar requisitos funcionais e não funcionais da funcionalidade de tarefas

**Comment by gabrielalbino** [comment]
Já coloquei lá no [drive](https://docs.google.com/document/d/1re2mmIpJoOhukczDvyLPJlMn0rctEXj2RsV6TF-qFzs/)
