### ISSUE TITLE
Elicitar requisitos funcionais e não funcionais: Lojas

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#42]
# Issue Template

## Descrição da Issue
Elicitar requisitos funcionais e não funcionais da funcionalidade de loja

**Comment by lucasdutraf** [comment]
Galera, está feito! Está no [drive](https://docs.google.com/document/d/1I0VVzaWyZzRWTypUAFgMd-q_Hr0x_YOLG2tWfVdJ-Gc/edit#) e gostaria que vocês dessem uma revisada e me dizerem o que acharam!
Não consegui levantar nenhum requisito não funcional, se puderem me ajudar nesta parte!
