### ISSUE TITLE
Elicitar requisitos funcionais e não funcionais: Inventario

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#43]
# Issue Template

## Descrição da Issue
Elicitar requisitos funcionais e não funcionais da funcionalidade de inventario

**Comment by rogerioo** [comment]
O documento já está disponível no [Drive](https://docs.google.com/document/d/13vd3KbvCI7g0MkmvZwU2fZzdik3-g9ccbrXnNdoKEaw/edit?usp=sharing)
