### ISSUE TITLE
Elicitar requisitos funcionais e não funcionais: Desafios

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#44]
# Issue Template

## Descrição da Issue
Elicitar requisitos funcionais e não funcionais da funcionalidade de desafios

**Comment by kaiquebuilds** [comment]
Feito e já está no [drive](https://docs.google.com/document/d/1DCBIeaUZNmx4FFXoV4rlt87dQeESWTSbHErAdNrCEvc/edit?usp=sharing)
