### ISSUE TITLE
Pirorização: MoSCoW

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#45]
# Issue Template

## Descrição da Issue
Depois de elicitar os requisitos e ter as informações do questionario sobre eles, o grupo irá produzir uma tabela MoSCoW com os resultados.

**Comment by gabrielalbino** [comment]
O artefato encontra-se no [drive](https://drive.google.com/open?id=1PQE3AH-Ict6UgrDtjFWoeVYA7h9-tpHYiFZsj3imoAU)

**Comment by rogerioo** [comment]
Tarefa realizada e entregue.
