### ISSUE TITLE
Técnicas de Elicitação: Etnografia

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#48]
# Issue Template

## Descrição da Issue
De acordo com o que foi apresentado em aula, produzir uma etnografia que faça sentido no contexto da aplicação da equipe.

### Tasks:
- [ ] Confeccionar um artefato que utilize a técnica de etnografia
- [ ] Buscar explicitar uma visão completa e ajustada no contexto da aplicação

## Assignees
@Phe0

**Comment by rogerioo** [comment]
Artefato não entregue.

**Comment by Phe0** [comment]
Documento de etnografica com priorização MOSCOW, feito para entrega idnividual
https://docs.google.com/document/d/1wxXU4AOnlJTJIE9xkW4flzigUmPQcg5mxb8mrIiS1mk/edit
