### ISSUE TITLE
Técnicas de Elicitação: Análise de Discurso

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#49]
# Issue Template

## Descrição da Issue
De acordo com o que foi apresentado em aula, produzir uma análise do discurso que faça sentido no contexto da aplicação da equipe.

### Tasks:
- [x] Confeccionar artefato que explicite o uso da análise do discurso

## Assignees
@kaiqueborges

**Comment by kaiquebuilds** [comment]
De acordo com a Análise de Protocolo 1 (AP1) e a Análise de Protocolo 2 (AP2), um entendimento maior sobre a organização de tarefas de estudantes foi adquirida e alguns requisitos foram inferidos.

Em AP1, um vídeo foi gravado no dia 08/04/2019 e AP2 é o conjunto de um áudio e fotos feitos em 09/04/2019.

AP1 teve pouca utilidade, já que o indivíduo não costuma externalizar suas tarefas a serem feitas. Já o indivíduo de AP2 explicou detalhadamente como funciona seu sistema de organização tanto para o trabalho quanto para os estudos, em um momento em que planejava seu dia seguinte.

Os requisitos extraídos disso foram: 

**- O usuário deve ser capaz de guardar tarefas.**
	Surge de AP1 e AP2 - mais de AP2 que de AP1 - onde relatam que às vezes se lembrar de tudo não é possível, precisando externalizar as atividades.

**- O usuário deve ser capaz de guardar tarefas recorrentes.**
	Surge a partir de uma extrapolação de AP2. As tarefas que ocorrem todos os dias não são colocadas na agenda, perdendo assim o rastro e muitas vezes é esquecida. Também é um trabalho repetitivo e cansativo ter de escrever essas tarefas todos os dias na agenda.

**- O usuário deve ser capaz de definir uma data limite para as tarefas.**
	Surge de AP2, onde o indivíduo relata colocar em sua agenda os eventos e tarefas nas datas onde devem ser feitas.

**- O usuário deve ser capaz de marcar uma tarefa como concluída.**
	Surge de AP2, onde o indivíduo relata marcar as tarefas com "OK" assim que são feitas, para manter controle da sua produtividade.

**- O usuário deve ser capaz de categorizar tarefas**
	Surge de AP1 e AP2, onde os indivíduos relatam separar tarefas de estudos de tarefas do trabalho.

**Comment by kaiquebuilds** [comment]
O documento se encontra [aqui](https://docs.google.com/document/d/1kwi4Vgbd9eYcfC37XIWsU-u-GmwzrT9PdGfnRd8V5YM/edit?usp=sharing)
