### ISSUE TITLE
Técnicas de Elicitação: Entrevista

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#50]
# Issue Template

## Descrição da Issue
De acordo com o que foi apresentado em aula, produzir uma entrevista que faça sentido no contexto da aplicação da equipe.

### Tasks:
- [x] Confeccionar um artefato que utilize a técnica de entrevista
- [x] Propor entrevista com alguém que seja relevante ao projeto

## Assignees
@devsalula

**Comment by rogerioo** [comment]
O [Saleh](@devsalula ) obteve contato com o criador do Habitica Brasil que propôs uma entrevista com os integrantes a ser marcada essa semana, no máximo até segunda-feira que vem.

**Comment by lucasdutraf** [comment]
@devsalula , assim que elaborar as perguntas, coloca elas aqui ou o link para o drive

**Comment by devsalula** [comment]
Reunião marcada para o dia 15/04 às 18:30

**Comment by devsalula** [comment]
Entrevista realizada. Falta apenas refinar o documento.

**Comment by lucasdutraf** [comment]
@devsalula é válido postar aqui mesmo sem refinar como uma v1.0?
