### ISSUE TITLE
Priorização: First Things First

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#52]
# Issue Template

## Descrição da Issue
De acordo com o que foi apresentado em aula, produzir uma *First Things First* que faça sentido no contexto da aplicação da equipe.

### Tasks:
- [x] Confeccionar um artefato para o First Things First

## Assignees
@gabrielalbino

**Comment by gabrielalbino** [comment]
O artefato encontra-se no [drive](https://drive.google.com/open?id=12C2NhMU5GYeHp1ebss8QKe49tTRONl9pUFTK_Zp-dc8)

**Comment by rogerioo** [comment]
Tarefa concluída e entregue.
