### ISSUE TITLE
Cenários e Léxico - Feature: Inventário

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#55]
# Cenários e Léxico - Feature: Inventário

**Comment by rogerioo** [comment]
V 1.0

# Cenários

## CENÁRIO 001

### Título

***

Chocar ovos de Pets

### Objetivo

***

Chocar o ovo para que o usuário possua um novo pet

### Contexto

***

* Local: Inventário
* Tempo: Enquanto estiver usando o Habitica
* Pré-condição: O usuário deve estar logado

### Atores

***

Usuário

### Recursos

***

* Ovo
* Poção de Eclosão
* Internet
* Computador ou Celular

### Episódios

***

* Usuário compra ovo de pet na loja
* Usuário ganha ovo de pet relizando tarefas
* Usuário compra poção de eclosão na loja
* Usuário ganha poção de eclosão realizando tarefas
* Usuário aplica poção de eclosão no ovo do pet
* O ovo choca
* Pet nasce com a cor da poção usada

### Restrição

***

* Usuário deve ter ovos de pet disponíveis no inventário
* Usuário deve ter poção de eclosão para chocar o ovo

### Exceção

***

* Falta de conexão à internet
* Falta de aparelho mobile ou computador

**Comment by rogerioo** [comment]
V 1.0

# Léxicos

## Ovo de Pet

### Nome

***

Ovo de Pet

### Sinônimos

***

Ovos de Pets

### Noção

***

* Recipiente que guarda um pet até que ele seja chocado e possa nascer
* Usuário possui novo pet
* Costomizar o avatar do usuário com o pet

### Impacto

***

* Pet pode ser alimentado
* Pet pode evoluir

### Classificação

***

Objeto

## Ovo Choca

### Nome

***

Ovos chocam

### Sinônimos

***

Ovos chocam

### Noção

***

* Tarefa relizada pelo usuário
* Acontece quando o usuário aplica poção de eclosão no ovo
* Processo que permite que um pet nasça

### Impacto

***

* O pet nasceu
* O pet pode ser alimentado
* o pet pode evoluir a partir da comida
* Usuário pode costumizar avatar com o pet

### Classificação

***

Verbo

## Evoluir

### Nome

***

Evoluir

### Sinônimos

***

--

### Noção

***

* Ocorre quando o pet é alimentado
* Muda de nível
* Aumentado o nível ele muda de forma

### Impacto

***

* O usuário fica mais motivado
* O pet causa mais danos em meio a desafios e missões

### Classificação

***

Estado

**Comment by rogerioo** [comment]
Primeira versão feita, aguardando avaliação do time e dos professores. Para versões futuras pretendo fazer mais cenários e léxicos, pois o tempo foi curto.

**Comment by rogerioo** [comment]
Segunda versão dos cenários disponível no [drive](https://docs.google.com/document/d/12V85cobsEAWZK6OD7kEcCgMprOz8ymgW4f9vGCUio1I/edit?usp=sharing).
Segunda versão dos léxicos disponível no [drive](https://docs.google.com/document/d/1_XO_bzBpEBtL5PncW-mFPtPUnDSCS28DZBrNEME2-g0/edit?usp=sharing).
