### ISSUE TITLE
Cenários e Léxico - Feature: Desafios

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#56]
# Cenários e Léxico - Feature: Desafios

**Comment by kaiquebuilds** [comment]
# V1

Título | Criar desafio público
-- | --
Objetivo | Criar um novo desafio público
Contexto | **Pré-condição**: O usuário deve estar logado - **Local**:  Desafios - **Tempo**:  Em qualquer momento
Atores | Usuários que queiram criar uma competição em cima de algum objetivo
Recursos | Gemas - prêmio do desafio; Moedas, saúde, experiência - indiretamente, através das tarefas do desafio
Episódios | Usuário abre o app; Usuário clica em desafios; Usuário clica em "criar desafio"; Usuário digita informações do desafio; Usuário salva o afazer; Usuário adiciona tarefas do desafio;
Restrição | Usuário não descrever bem o desafio;
Exceção | Usuário não ter 1 (uma) ou mais Gemas para servirem de prêmio do desafio.

Título | Entrar em um desafio público
-- | --
Objetivo | Participar de um desafio público
Contexto | **Pré-condição**: O usuário deve estar logado - **Local**:  Desafios - **Tempo**:  Em qualquer momento
Atores | Usuários que queiram participar uma competição em cima de algum objetivo
Recursos | Gemas - prêmio do desafio; Moedas, saúde, experiência - indiretamente, através das tarefas do desafio
Episódios | Usuário abre o app; Usuário clica em desafios; Usuário clica em "encontre desafio"; Usuário o faz uma busca por texto (opcional); Usuário filtra os desafios por categoria (opcional); Usuário clica no título do desafio; Usuário clica em "se juntar ao desafio".
Restrição | Usuário escolher um desafio que não consegui cumprir
Exceção | Usuário não ter uma conta

Título | Ver progresso de participantes de um desafio
-- | --
Objetivo | Ver o progresso de outros participantes de algum desafio
Contexto | **Pré-condição**: O usuário estar logado - **Local**:  Desafios - **Tempo**:  Em qualquer momento
Atores | Usuários participantes do desafio; Usuário comum.
Recursos | Conexão com a internet
Episódios | Usuário abre o app; Usuário clica em desafios; Usuário o faz uma busca por texto (opcional); Usuário filtra os desafios por categoria (opcional); Usuário clica no título do desafio; Usuário clica em "selecione um participante"; Usuário pesquisa nome do participante (opcional); Usuário clica no nome do participante.
Restrição |
Exceção | O desafio não ter participantes

Título | Declarar vencedor de um desafio
-- | --
Objetivo | Declarar o vencedor de algum desafio e dar o prêmio a ele(a)
Contexto | **Pré-condição**: O usuário estar logado - **Local**:  Desafios - **Tempo**:  Em qualquer momento
Atores | Usuários participantes do desafio; Usuário criador do desafio.
Recursos | Conexão com a internet
Episódios | Usuário abre o app; Usuário clica em desafios; Usuário o faz uma busca por texto (opcional); Usuário filtra os desafios por categoria (opcional); Usuário clica no título do desafio; Usuário clica em "selecione um participante"; Usuário pesquisa nome do participante (opcional); Usuário clica no nome do participante; Usuário clica em "Vencedor do desafio".
Restrição |
Exceção | O usuário não ser o criador do desafio
