### ISSUE TITLE
Cenários e Léxico - Feature: Tarefas

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#57]
# Cenários e Léxico - Feature: Tarefas

**Comment by gabrielalbino** [comment]
# Cenário V1, V2 e JSON
## V1 (Não é a ultima versão)
Título | Adicionar tarefa diária
-- | --
Objetivo | Adicionar uma tarefa na lista de tarefas diárias
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
Episódios | Usuário abre o app; Usuário entra no menu de criação da diária; Usuário digita informações da tarefa; Usuário salva a tarefa;
Restrição | Usuário não preenche as informações da diária corretamente
Exceção | Usuário não ter uma conta


Título | Adicionar um afazer
-- | --
Objetivo | Adicionar uma tarefa na lista de afazeres
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
Episódios | Usuário abre o app; Usuário clica em criar afazeres; Usuário digita informações do afazer; Usuário salva o afazer;
Restrição | Usuário não preenche as informações do afazer corretamente
Exceção | Usuário não ter uma conta


Título | Adicionar um hábito
-- | --
Objetivo | Adicionar uma tarefa na lista de hábitos
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
Episódios | Usuário abre o app; Usuário clica em criar hábito; Usuário digita informações do hábito; Usuário salva o hábito
Restrição | Usuário não preenche as informações do hábito corretamente
Exceção | Usuário não ter uma conta


Título | Completar Tarefas
-- | --
Objetivo | Completar uma tarefa da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas, Sistema
Episódios | Usuário abre o app; Usuário clica em tarefas; Usuário marca a tarefa diária como completa; Sistema dá a recompensa ao usuário; Sistema renova a tarefa de acordo com o tempo que o usuário definiu na criação da tarefa;
Restrição | Usuário não preenche as informações da tarefa corretamente
Exceção | Usuário não ter uma conta; Usuário não ter tarefas cadastradas;


Título | Completar Afazeres
-- | --
Objetivo | Completar um afazer da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas, Sistema
Episódios | Usuário abre o app; Usuário clica em afazeres; Usuário marca o afazer como completo; Sistema dá a recompensa ao usuário; Sistema oculta o afazer da lista de afazeres;
Restrição | Usuário não preenche as informações do afazer corretamente
Exceção | Usuário não ter uma conta; Usuário não ter afazeres cadastradas;


Título | Preencher Hábitos
-- | --
Objetivo | Incrementar um hábito da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas, Sistema
Episódios | Usuário abre o app; Usuário clica em hábitos; Usuário marca se completou um hábito bom ou ruim; Sistema contabiliza o hábito bom/ruim e dá recompensas/desvantagens ao usuário;
Restrição | Usuário não preenche as informações do hábito corretamente;
Exceção | Usuário não ter uma conta; Usuário não ter hábitos cadastradas


Título | Cadastrar Recompensas Customizadas
-- | --
Objetivo | Cadastrar uma recompensa para ser comprada
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas, Sistema
Episódios | Usuário abre o app; Usuário clica “Cadastrar Recompensas”; Usuário preenche o texto, o valor e alguma observação sobre a recompensa.; Sistema passa a exibir a nova recompensa na lista de recompensas; Usuário agora pode comprar recompensas customizadas;
Restrição | Usuário não preenche as informações da recompensa corretamente
Exceção | Usuário não ter uma conta


Título | Comprar Recompensas Customizadas
-- | --
Objetivo | Comprar uma recompensa customizada
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas, Sistema
Episódios | Usuário abre o app; Usuário clica em “Recompensas”; Usuário clica no valor da recompensa desejada; Sistema retira as moedas do usuário e dá o cartão de recompensa a ele;
Restrição | Usuário não preenche as informações da recompensa corretamente; Usuário não tem recompensas customizadas cadastradas;
Exceção | Usuário não ter uma conta

## V2 (Atualmente é a ultima versão)

Título | Adicionar tarefa diária
-- | --
Objetivo | Adicionar uma tarefa na lista de tarefas diárias
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário entra no menu de criação da diária; Usuário digita informações da tarefa; Usuário salva a tarefa;
Restrição | Usuário não preenche as informações da diária corretamente
Exceção | Usuário não ter uma conta


Título | Adicionar um afazer
-- | --
Objetivo | Adicionar uma tarefa na lista de afazeres
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em criar afazeres; Usuário digita informações do afazer; Usuário salva o afazer;
Restrição | Usuário não preenche as informações do afazer corretamente
Exceção | Usuário não ter uma conta


Título | Adicionar um hábito
-- | --
Objetivo | Adicionar uma tarefa na lista de hábitos
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em criar hábito; Usuário digita informações do hábito; Usuário salva o hábito;
Restrição | Usuário não preenche as informações do hábito corretamente
Exceção | Usuário não ter uma conta


Título | Completar Tarefas
-- | --
Objetivo | Completar uma tarefa da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em tarefas; Usuário marca a tarefa diária como completa; Sistema dá a recompensa ao usuário; Sistema renova a tarefa de acordo com o tempo que o usuário definiu na criação da tarefa;
Restrição | Usuário não preenche as informações da tarefa corretamente
Exceção | Usuário não ter uma conta; Usuário não ter tarefas cadastradas


Título | Completar Afazeres
-- | --
Objetivo | Completar um afazer da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em afazeres; Usuário marca o afazer como completo; Sistema dá a recompensa ao usuário; Sistema oculta o afazer da lista de afazeres;
Restrição | Usuário não preenche as informações do afazer corretamente
Exceção | Usuário não ter uma conta; Usuário não ter afazeres cadastradas


Título | Preencher Hábitos
-- | --
Objetivo | Incrementar um hábito da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em hábitos; Usuário marca se completou um hábito bom ou ruim; Sistema contabiliza o hábito bom/ruim e dá recompensas/desvantagens ao usuário;
Restrição | Usuário não preenche as informações do hábito corretamente
Exceção | Usuário não ter uma conta; Usuário não ter hábitos cadastradas


Título | Cadastrar Recompensas Customizadas
-- | --
Objetivo | Cadastrar uma recompensa para ser comprada
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Ouro
‘Episódios | Usuário abre o app; Usuário clica “Cadastrar Recompensas”; Usuário preenche o texto, o valor e alguma observação sobre a recompensa.; Sistema passa a exibir a nova recompensa na lista de recompensas; Usuário agora pode comprar recompensas customizadas;
Restrição | Usuário não preenche as informações da recompensa corretamente
Exceção | Usuário não ter uma conta


Título | Comprar Recompensas Customizadas
-- | --
Objetivo | Comprar uma recompensa customizada
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Ouro
‘Episódios | Usuário abre o app; Usuário clica em “Recompensas”; Usuário clica no valor da recompensa desejada; Sistema retira as moedas do usuário e dá o cartão de recompensa a ele;
Restrição | Usuário não preenche as informações da recompensa corretamente
Exceção | Usuário não ter uma conta; Usuário não tem recompensas customizadas cadastradas


Título | Editar Hábito
-- | --
Objetivo | Editar um hábito da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em “Hábitos” e seleciona um hábito cadastrado; Usuário escolhe as novas informações do hábito e salva; Sistema atualiza o hábito e exibe o hábito atualizado ao usuário;
Restrição | Usuário não tem hábitos cadastrado
Exceção | Usuário não ter uma conta


Título | Editar Tarefa Diária
-- | --
Objetivo | Editar uma tarefa da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em “Tarefas” e escolhe a tarefa que será atualizada; Usuário preenche as novas informações  e salva; Sistema atualiza a tarefa e exibe ela atualizada ao usuário;
Restrição | Usuário não tem tarefas cadastrado
Exceção | Usuário não ter uma conta


Título | Editar Afazeres
-- | --
Objetivo | Editar um afazer da lista
Contexto | **Local:** Tela inicial **Tempo:** Em qualquer momento **Pré-condição:** Usuário deve estar logado
Atores | Usuário, Sistema
Recursos | Tarefas
‘Episódios | Usuário abre o app; Usuário clica em “Afazeres” e seleciona o afazer que deseja editar; Usuário preenche as novas informações do afazer e salva; Sistema atualiza o afazer e exibe-o ao usuário com informações atualizadas;
Restrição | Usuário não tem afazeres cadastrado
Exceção | Usuário não ter uma conta

## JSON da V2

```
[  
   {  
        "title": "Adicionar tarefa diária",
        "objective": "Adicionar uma tarefa na lista de tarefas diárias",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário entra no menu de criação da diária",
            "Usuário digita informações da tarefa",
            "Usuário salva a tarefa"
        ],
        "restriction": "Usuário não preenche as informações da diária corretamente",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Adicionar um afazer",
        "objective": "Adicionar uma tarefa na lista de afazeres",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em criar afazeres",
            "Usuário digita informações do afazer",
            "Usuário salva o afazer"
        ],
        "restriction": "Usuário não preenche as informações do afazer corretamente",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Adicionar um hábito",
        "objective": "Adicionar uma tarefa na lista de hábitos",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em criar hábito",
            "Usuário digita informações do hábito",
            "Usuário salva o hábito"
        ],
        "restriction": "Usuário não preenche as informações do hábito corretamente",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Completar Tarefas",
        "objective": "Completar uma tarefa da lista ",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em tarefas",
            "Usuário marca a tarefa diária como completa",
            "Sistema dá a recompensa ao usuário",
            "Sistema renova a tarefa de acordo com o tempo que o usuário definiu na criação da tarefa"
        ],
        "restriction": "Usuário não preenche as informações da tarefa corretamente",
        "exception": "Usuário não ter uma conta, Usuário não ter tarefas cadastradas"
   },
   {  
        "title": "Completar Afazeres",
        "objective": "Completar um afazer da lista",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em afazeres",
            "Usuário marca o afazer como completo",
            "Sistema dá a recompensa ao usuário",
            "Sistema oculta o afazer da lista de afazeres"
        ],
        "restriction": "Usuário não preenche as informações do afazer corretamente",
        "exception": "Usuário não ter uma conta, Usuário não ter afazeres cadastradas"
   },
   {  
        "title": "Preencher Hábitos",
        "objective": "Incrementar um hábito da lista",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em hábitos",
            "Usuário marca se completou um hábito bom ou ruim",
            "Sistema contabiliza o hábito bom/ruim e dá recompensas/desvantagens ao usuário"
        ],
        "restriction": "Usuário não preenche as informações do afazer corretamente",
        "exception": "Usuário não ter uma conta, Usuário não ter hábitos cadastradas"
   },
   {  
        "title": "Cadastrar Recompensas Customizadas",
        "objective": "Cadastrar uma recompensa para ser comprada",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Ouro",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica “Cadastrar Recompensas",
            "Usuário preenche o texto, o valor e alguma observação sobre a recompensa",
            "Sistema passa a exibir a nova recompensa na lista de recompensas",
            "Usuário agora pode comprar recompensas customizadas"
        ],
        "restriction": "Usuário não preenche as informações da recompensa corretamente",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Comprar Recompensas Customizadas",
        "objective": "Comprar uma recompensa customizada",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Ouro",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em “Recompensas",
            "Usuário clica no valor da recompensa desejada",
            "Sistema retira as moedas do usuário e dá o cartão de recompensa a ele"
        ],
        "restriction": "Usuário não preenche as informações da recompensa corretamente",
        "exception": "Usuário não ter uma conta, Usuário não tem recompensas customizadas cadastradas"
   },
   {  
        "title": "Editar Hábito",
        "objective": "Editar um hábito da lista",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em “Hábitos” e seleciona um hábito cadastrado",
            "Usuário escolhe as novas informações do hábito e salva",
            "Sistema atualiza o hábito e exibe o hábito atualizado ao usuário"
        ],
        "restriction": "Usuário não tem hábitos cadastrado",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Editar Tarefa Diária",
        "objective": "Editar uma tarefa da lista",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em Tarefas e seleciona uma tarefa cadastrado",
            "Usuário escolhe as novas informações da tarefa e salva",
            "Sistema atualiza a tarefa e exibe a tarefa atualizada ao usuário"
        ],
        "restriction": "Usuário não tem tarefas cadastradas",
        "exception": "Usuário não ter uma conta"
   },
   {  
        "title": "Editar Afazeres",
        "objective": "Editar um afazer da lista",
        "context":{  
            "pre-condition": "Usuário deve estar logado",
            "local": " Tela inicial",
            "time": "Em qualquer momento"
        },
        "actors": "Usuário, Sistema",
        "resources": "Tarefas",
        "episodes": [  
            "Usuário abre o app",
            "Usuário clica em "afazeres" e seleciona um afazer cadastrado",
            "Usuário escolhe as novas informações do afazer e salva",
            "Sistema atualiza o afazer e exibe o afazer atualizado ao usuário"
        ],
        "restriction": "Usuário não tem afazer cadastrado",
        "exception": "Usuário não ter uma conta"
   }
]
```
