### ISSUE TITLE
Cenários e Léxico - Feature: Guia de Contribuição

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#59]
# Cenários e Léxico - Feature: Guia de Contribuição

- [x] Levantar Cenários
- [x] Levantar Léxicos
- [x] Modelar Cenário de Contribuição para o código
- [x] Modelar o Cenário de Contribuição para a documentação
- [x] Modelar o Cenário de Contribuição para traduzir o app
- [x] Modelar Cenário de Contribuição para o design
- [ ] <s>Modelar Cenário de Contribuição para as músicas</s> (Não aceitam mais)
- [x] Modelar Cenário de Contribuição para  a narrativa (história)
- [ ] <s>Modelar Cenário de Contribuição para as estatísticas</s> (Não usam mais)
- [x] Modelar Cenário de Contribuição para desenhistas (pixel art)
- [x] Repassar tudo para JSON
- [x] Repassar tudo para REACT

**Comment by devsalula** [comment]
Está tudo presente dentro do documento [Cenário - Guia de Contribuição. v1](https://docs.google.com/document/d/1yMonLC6sh2XLvwkBmu-ZIT9kaz7o07vPOjnVLNoAh7E/edit)

**Comment by devsalula** [comment]
Remodelei os [cenários](https://docs.google.com/document/d/1EuPigzmBNujwNnIpvZ1NRuN2wsimj0uztfUSRgh-Poo/edit) e levantei os [léxicos](https://docs.google.com/document/d/1SWoOEEwNNr-RYneWHjfWW7lkt6fmK8JtCVd0sqND8_U/edit).

**Comment by devsalula** [comment]
@EsioFreitas todos os [cenários](https://docs.google.com/document/d/1EuPigzmBNujwNnIpvZ1NRuN2wsimj0uztfUSRgh-Poo/edit#heading=h.hudc49utub0e) e [léxicos](https://docs.google.com/document/d/1SWoOEEwNNr-RYneWHjfWW7lkt6fmK8JtCVd0sqND8_U/edit#) já em JSON. 
Olha no final dos arquivos.
