### ISSUE TITLE
Montar V2 da argumentação da escolha de tema

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#6]
## Descrição da Issue
É necessário incluir nos rastros do grupo a discussão fomentada a respeito da abordagem utilizada pelo grupo para a primeira entrega no modelo Argumentação.
Montar segunda versão da argumentação feita para a escolha do tema do grupo, dessa vez incluindo os argumentos utilizados para os outros apps levantados

### Tasks:
- [x] Pesquisar sobre dissipação de conflitos no modelo argumentativo 
- [x] Levantar Proposições
- [x] Inserir conflitos, inferências e preferências

**Comment by EsioFreitas** [comment]
i(p1) Féo: Ribon - temos contato com os criadores.
i(p2) Féo: PicPay - acho que é um app completo. 
i(p3) Féo: Warren - nunca vi.
i(p4) Féo: Yellow - é um app novo e legal, mas só dá pra usar no plano e águas e isso é inviável. 
i(p5) Féo: Habitica - é open source então temos acesso ao código e é um app legal.
i(p6) Féo: Netflix - sem opiniões fortes.
i(p7) Féo: Draw.io - sem opiniões fortes.
i(p8) Youssef: Achei muito fofo esse habitica
i(p9) Ésio: Ribon - Não esto animado com ele.
i(p10) Ésio: PicPay - legal, mas acho que temos melhores opções.
i(p11) Ésio: Warren -  Tava muito empolgado, mas acho o escopo enorme hj.
i(p12) Ésio: Yellow - inviavel.
i(p13) Ésio: Habitica - achei muito interessante. 
i(p14) Ésio: Netflix -  Não esto animado com ele.
i(p15) Ésio: Draw.io -  legal, mas acho que temos melhores opcoes
i(p16) Dutra: a cores do habitica ja me conquistaram.
i(p17) Youssef: Mas a UX não tá tão boa, não me conquistou e tem bastante coisa também;
i(p18) Rogerioo: Ribon - Muito bacana, mas não acho que vá ser tão proveitoso, o escopo parece bem pequeno, pelo o que entendi
i(p19) Rogerioo: PicPay -gostei, também é uma opção
i(p20) Rogerioo: Warren -  É top, mas app de investimento e com Machine Learning acho que vai ser muito foda
i(p21) Rogerioo: Yellow - Interessante, mas sou sedentário hahaha
i(p22) Rogerioo: Habitica - Muito massa, bora organizar a vida
i(p23) Rogerioo: Netflix - acho que o escopo vai ser muito grande 
i(p24) Rogerioo: Draw.io - não sou muito fã;
P1(i(p22), i(p17)): Time decidiu continuar com Habitica;
P2(i(p18), i(p19)): votação: PicPay x Ribon;
i(p25) Saleh: PicPay realmente é melhor;
i(p26) Gabriel Albino: Ninguem gostou do Warren e do Yellow;
i(p27) Youssef: Ninguem gostou do Netflix e do Draw.io tambem;
P3(i(p25), i(p22)): votação habitica X PicPay;

**Comment by rogerioo** [comment]
Tá ótimo @EsioFreitas!

**Comment by EsioFreitas** [comment]
![escolhaTemaV2 (1)](https://user-images.githubusercontent.com/34384624/55295492-16b32980-53e4-11e9-91ed-8edf016f5e88.png)
