### ISSUE TITLE
Cenários e Léxico - Feature: Gamificação

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#60]
# Cenários e Léxico - Feature: Gamificação

- [x] Levantar Léxicos
- [x] Levantar Cenários
- [x] Elaborar Léxicos
- [x] Elaborar Cenários
- [x] Passar Cenários para o Padrão REACT
- [x] Passar Léxicos para o Padrão REACT

**Comment by Phe0** [comment]
Comecei a fazer os cenários, vou levar esses para a pré entrega, para o Seminário faço os demais e os léxicos
https://docs.google.com/document/d/1MbZ7XK-luTqImqMyBrspIZsXeInaHwU4u3mHrghYrOs/edit

**Comment by Phe0** [comment]
Os cenários foram listados no link: 
https://docs.google.com/document/d/1d3u-eConUOme_QzqpTTBtUeCe5vuszEnim4G5m_5SaE/edit
Os cenários foram elaborados no link: https://docs.google.com/document/d/15AFu13HFu2P_7JqAabbbj_eWXRHyhFIh7NL2N01BMPo/edit
Os Léxicos foram listados no link: https://docs.google.com/document/d/16Lpf5Ar18XdWKJxl6gX4IgjgpRRSuCakA-UEaps2DVc/edit

**Comment by Phe0** [comment]
V2 dos cenários:
https://docs.google.com/document/d/15AFu13HFu2P_7JqAabbbj_eWXRHyhFIh7NL2N01BMPo/edit

V1 dos léxicos:
https://docs.google.com/document/d/1LlzaRV0L72efy0RYBU78lNc1AN-A6NkZpB5eLyhEBn4/edit
