### ISSUE TITLE
Léxicos: Template

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#65]
Título | Definições
:--: | :--
Nome | Léxico
Sinônimos | Variantes do nome que se refiram à mesma coisa (plural, etc.)
Noção | Definições que possam contextualizar o léxico. Quanto mais melhor; **Verbo**: Quem realiza, quando acontece e quais os procedimentos envolvidos; **Objeto**: Definir o objeto e o relacionamento que tem com outros; **Estado**: O que significa e o que leva a esse estado
Impacto | Devem ter explicitado o que o léxico impacta em outros. Tem que citar o nome; **Verbo**: Quais os reflexos e o que decorreu; **Objeto**:Ações que podem ser aplicadas ao objeto; **Estado**: Outros estados e ações que se decorrem a partir desse estado
Classificação | Verbo, objeto ou estado

As noções e o impactos devem ser em tópicos

**Comment by Phe0** [comment]
## JSON

```
[  
   {  
      "name":"#",
      "synonyms":[  
         "#",
         "#",
         "#",
         "#"
      ],
      "notion":[  
         "#",
         "#",
         "#"
      ],
      "impact":[  
         "#",
         "#"
      ],
      "classification":"#"
   }
]
```

**Comment by youssef-md** [comment]
Seguindo o mesmo padrão para os cenários, mudem o nome 'Base' para o nome do Léxico, ex: Lexico07v1 e para os links 
```
import React from 'react'
import { Link } from 'react-router-dom'

const Base = () => (
  <div className="content artefact">
    <HeadArtefact versions={ null } rastreability={ null }
                  title="Artefato Nome" author="Quem fez"/>
    <Card>
      <h2>Nome</h2>
      <p>Irure pariatur Lorem ea commodo tempor magna.</p>
    </Card>

    <Card>
      <h2>Sinônimos</h2>
      <ul>
        <li>Esse sint <Link to="/Lexico04v2">Léxico04</Link></li>
      </ul>
    </Card>

    <Card>
      <h2>Noção</h2>
      <ul>
        <li>Reprehenderit sit adipisicing sunt tempor fugiat dolore eiusmod ea ad dolor.</li>
      </ul>
    </Card>

    <Card>
      <h2>Impacto</h2>
      <ul>
        <li><Link to="/Contexto02v2">Léxico02</Link> aliqua</li>
        <li>Aute incididunt pariatur ex dolore dolore culpa aliqua id ex minim velit.</li>
      </ul>
    </Card>

    <Card>
      <h2>Classificação</h2>
      <p>Et veniam pariatur qui duis adipisicing.</p>
    </Card>

  </div>
)

export default Base
```

**Comment by youssef-md** [comment]
Como exemplo fiz o primeiro léxico deste doc: https://docs.google.com/document/d/1MqgL6LctCnf7vB0_NCUlOFBeJQ2jrOvjbq1B5Jgd348/edit

```
import React from 'react'
import { Link } from 'react-router-dom'

const Tarefav2 = () => (
  <div className="content artefact">
    <HeadArtefact versions={ null } rastreability={ null }
                  title="Tarefa" author="Josezin"/>
    <Card>
      <h2>Nome</h2>
      <p>Tarefa</p>
    </Card>

    <Card>
      <h2>Sinônimos</h2>
      <ul>
        <li>Tarefas</li>
        <li>Task</li>
        <li>Tasks</li>
      </ul>
    </Card>

    <Card>
      <h2>Noção</h2>
      <ul>
        <li>
          Tarefa é o conceito chave do habitica, o usuário pode ter 3 tipos de tarefas,
          e cada uma pertence a uma lista de tarefas: <Link to="/TarefaDiariav1">diárias</Link>
          <Link to="/Afazerv1">afazeres</Link> <Link to="/TarefaDiariav1">hábitos</Link>
        </li>
      </ul>
    </Card>

    <Card>
      <h2>Impacto</h2>
      <ul>
        <li>Ao realizar tarefas o usuário ganha recompensas</li>
        <li>Ao não realizar as tarefas o avatar pode perder vida</li>
      </ul>
    </Card>

    <Card>
      <h2>Classificação</h2>
      <p>Objeto</p>
    </Card>

  </div>
)

export default Tarefav2

```

**Comment by youssef-md** [comment]
Consultem o Base.js dos Léxicos e Cenários da branch DocFramework pois atualizei os imports

**Comment by youssef-md** [comment]
Para utilizar o componente ```<Link>``` consultem os arquivos ```lexicos.js``` e/ou ```cenarios.js``` dentro de ```/utils``` pois o nome que está relacionado ao componente que deve ser referenciado ao utilizar o Link.

#### Exemplo
No arquivo ```/utils/lexicos.js``` tem o objeto "Tarefas" dentro de "lexic" tem o nome "Tarefa Diária" que se relaciona com o componente TarefaDiaria, então caso queira fazer um link para referenciar essa palavra em outro artefato ficaria assim ```<Link to="/ModelagemLexicos/Tarefa Diária" > tarefa diária </Link>```

E caso fosse um cenário seria ```to="/ModelagemCenarios/Tarefa Diária"```

Outra coisa importante! para abrir uma nova aba ao clicar no link(o que é melhor pra manter o contexto em que o usuário estava) basta colocar ```target="_blank"``` no Link: ```<Link to="" target="_blank">```

**Comment by rogerioo** [comment]
Issue sendo tratada por [essa](#82).
