### ISSUE TITLE
Elaborar artefato que documente a decisão do Rich Picture feito por todos os membros

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#7]
## Descrição da Issue
Após finalizarmos os Rich Pictures individuais, nos reuniremos para discutir e elaborar um RP global e rastrearemos através de um artefato criado utilizando o modelo de Argumentação.

**Comment by EsioFreitas** [comment]
![55126287-5aa7e500-50eb-11e9-8bdf-baf2f43a112d](https://user-images.githubusercontent.com/34384624/55250927-1b35e180-522e-11e9-8955-d19d189be259.jpg)

**Comment by EsioFreitas** [comment]
Gelera, add a parte 2 aqui.
