### ISSUE TITLE
Diagrama de Caso de Uso Contribuição

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#72]
## Descrição da Issue
Utilizar o diagrama de casos de uso para descrever uma parte do sistema do Habitica

### Tasks:
- [x] Esboço
- [x] Diagrama de Casos de Uso
- [x] Listar Cenários, Léxicos e Rich Pictures relacionados

**Comment by devsalula** [comment]
Atualizei o RP de Contribuição com um novo modelo.
![RPContribuiçãoV2](https://user-images.githubusercontent.com/35435199/56867996-e51d8600-69c2-11e9-922d-2de0ec0346c0.png)

**Comment by devsalula** [comment]
Atualizei os [cenários](https://docs.google.com/document/d/1KAUeAdH218Exbsac5FnUFGXnDuxnCS8PbK--Q1GLGMg/edit#).

**Comment by devsalula** [comment]
Meu trabalho foi realizado e está todo [aqui](https://drive.google.com/drive/folders/1vrcPdUNZ801f6SGdoV9kqt0V2HUZErn2?usp=sharing)
