### ISSUE TITLE
Diagrama de Casos de Uso Configuração

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#73]
## Descrição da Issue
Utilizar o diagrama de casos de uso para descrever uma parte do sistema do Habitica

### Tasks:
- [ ] Esboço
- [ ] Diagrama de Casos de Uso
- [ ] Listar Cenários, Léxicos e Rich Pictures relacionados

**Comment by rogerioo** [comment]
# UC20 - Comprar e enviar gemas

## 1 Nome do Caso de Uso
 	Comprar e enviar gemas

## 2 Breve descrição
  	O usuário navega até comprar gemas e compra gemas e depois as envia.

## 3 Atores
  	Usuário, sistema bancário.

## 4 Fluxo de eventos
### 4.1 Fluxo básico
Usuário escolhe o tanto de gema que deseja
Usuário preenche os dados do cartão
Usuário confirma a compra
Usuário compra as gemas
Usuário busca outro usuário
Usuário seleciona outro usuário
Usuário escreve mensagem
Usuário envia mensagem
  
### 4.2 Fluxos alternativos
Usuário escolhe o tanto de gema que deseja
Usuário escolhe uma forma de pagamento
Usuário confirma a compra
Usuário compra as gemas
Usuário busca outro usuário
Usuário seleciona outro usuário
Usuário escreve mensagem
Usuário envia mensagem

### 4.3 Fluxos de Exceção
Usuário escolhe o tanto de gema que deseja
Usuário escolhe uma forma de pagamento
Usuário não tem limite
Usuário é barrado de comprar as gemas

## 5 Pré-condições
  O usuário deve estar logado, o usuário deve possuir alguma forma de pagamento

## 6 Pós-condições
  Usuário recebe a quantidade de gemas que comprou.
