### ISSUE TITLE
Diagrama de Casos de Uso Desafios

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#75]
## Descrição da Issue
Utilizar o diagrama de casos de uso para descrever uma parte do sistema do Habitica

### Tasks:
- [x] Esboço
- [x] Diagrama de Casos de Uso
- [x] Listar Cenários, Léxicos e Rich Pictures relacionados

**Comment by kaiquebuilds** [comment]
O Diagrama se encontra [aqui](https://drive.google.com/file/d/1aYApJeTs7BObC72CiWMcUyOwkFBDHerv/view?usp=sharing)

Detalhamento dos casos de uso se encontra [aqui](https://docs.google.com/document/d/1T4wtYfV3vBSs5NDG-w_lLKzQ2oXMEzhyBZulwelK4Xk/edit?usp=sharing)

**Comment by youssef-md** [comment]
# UC01 - Criar desafio 
## 1. Nome do Caso de Uso 
Criar desafio

## 2. Breve descrição 
Criar um novo desafio público na comunidade do Habitica
## 3. Atores 
Usuário (Criador do desafio)
Sistema 
## 4. Fluxo de eventos 
### 4.1 Fluxo básico 
Usuário acessa seção “Desafios”
Usuário clica em “criar desafio”
Usuário digita informações do desafio
### 4.2 Fluxos alternativos 
Sem fluxos alternativos
### 4.3 Fluxos de Exceção 
FE01 - Usuário não possui gemas para usar como prêmio do desafio
Usuário não possui gemas suficientes 
Mensagem de alerta
Desafio não é criado
## 5. Pré-condições 
Usuário deve estar Logado no Sistema
## 6. Pós-condições 
Usuário possui um novo desafio
