### ISSUE TITLE
Diagrama de Casos de Uso Loja

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#77]
## Descrição da Issue
Utilizar o diagrama de casos de uso para descrever uma parte do sistema do Habitica

### Tasks:
- [ ] Esboço
- [ ] Diagrama de Casos de Uso
- [x] Listar Cenários, Léxicos e Rich Pictures relacionados

**Comment by youssef-md** [comment]
# UC15 - Comprar missão na loja
## 1 Nome do Caso de Uso
Comprar missão na loja
## 2 Breve descrição
O usuário navega até a loja da aplicação e adquire uma nova missão.
## 3 Atores
Usuário, sistema
## 4 Fluxo de eventos
### 4.1 Fluxo básico
Usuário faz login na aplicação
Usuário navega até a loja da aplicação
Usuário navega até a aba missões, dentro da loja
Usuário avalia o custo da missão comparado a seu saldo atual
Usuário compra a missão
### 4.2 Fluxos alternativos
FA01 - Comprar missão na Loja Sazonal
Usuário faz login na aplicação
Usuário navega até a loja da aplicação
Usuário navega até a aba Loja Sazonal, dentro da loja
Usuário avalia o custo da missão comparado a seu saldo atual
Usuário compra a missão
## 4.3 Fluxos de Exceção
FE01 - Missão a ser comprada é de um nível maior que a do usuário
Usuário faz login na aplicação
Usuário navega até a loja da aplicação
Usuário navega até a aba Missões, dentro da loja
Usuário avalia o custo da missão
Usuário é bloqueado por ser de um nível inferior ao requerido pela missão
## 5 Pré-condições
O usuário deve estar logado, o usuário deve possuir moedas ou gemas
## 6 Pós-condições
Usuário recebe uma nova missão para poder completar.
