### ISSUE TITLE
Diagrama de Casos de Uso Inventário

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#78]
## Descrição da Issue
Utilizar o diagrama de casos de uso para descrever uma parte do sistema do Habitica

### Tasks:
- [ ] Esboço
- [ ] Diagrama de Casos de Uso
- [ ] Listar Cenários, Léxicos e Rich Pictures relacionados

**Comment by rogerioo** [comment]
Diagrama:
- [Versão 01](https://drive.google.com/file/d/1_65D9hVT7fUe6TBFsxpTvI3Xofnvahcr/view?usp=sharing)
- [Versão 02](https://drive.google.com/file/d/1FbF5TnpLyQfdhhNnIkfDuW93Dz0I6Qse/view?usp=sharing)
- [Versão 03](https://drive.google.com/file/d/1YlQidfmUdU2qFp0xORcdjcJJxC3Jqd8T/view?usp=sharing)

Casos de Uso:
- [Versão 01](https://drive.google.com/file/d/1jqzAuk6sdLcCAyJrYTNEKiSjps90Ndvt/view?usp=sharing)

**Comment by rogerioo** [comment]
# UC28 - Chocar Ovos de Pet
## 1. Nome do Caso de Uso
  Chocar Ovos de Pet
## 2. Breve descrição
  Chocar ovos de pet com poção disponíveis no inventário para obter novo pet
## 3. Atores
  Usuário
       Sistema
## 4. Fluxo de eventos
### 4.1 Fluxo básico
  Usuário aplica poção de eclosão no ovo
        Obter novo pet
## 4.2 Fluxos alternativos
### FA01 - Comprar Ovo e/ou Poção Eclosão
  Usuário acessa a loja 
       Usuário procura por ovo e/ou poção de eclosão
       Usuário compra ovo e/ou poção de eclosão com moedas
       Usuário obtém ovo e/ou poção de eclosão
### FA02 - Realizar tarefa ou missão
  Usuário realiza tarefa ou missão
       Usuário pode obter ovo e/ou poção de eclosão
## 4.3 Fluxos de Exceção
FE01 - Usuário não possui gemas para adquirir ovos de pet e/ou poção de eclosão
  Usuário não possui gemas suficientes
        Usuário não obtém ovo e/ou poção de eclosão
## 5. Pré-condições
  Usuário deve estar Logado no Sistema
        Usuário deve possui ovo de pet
        Usuário deve possui poção de eclosão
## 6. Pós-condições
  Usuário possui um novo pet
