### ISSUE TITLE
Criar o NFR baseado no Habitica

### ISSUE THREAD

**Issue by devsalula** [requisitos-habitica/Habitica#85]
## Descrição da Issue
Construir um NFR, com base nos Requisitos Não Funcionais do Habitica. Leve em consideração: Usabilidade, Performance, Manutenibilidade, Segurança.

**Comment by Phe0** [comment]
V1 NFR Usabilidade
![image](https://user-images.githubusercontent.com/31973465/58435466-0a231880-8097-11e9-95f0-e778ccf170ba.png)

**Comment by youssef-md** [comment]
A versão 2 do NFR de usabilidade(que já inclui outros requisitos não funcionais) já está pronta [aqui](https://www.draw.io/?state=%7B%22ids%22:%5B%221c39hHC-_zPg2Y4fasHNSlGnUWOxVY4Bx%22%5D,%22action%22:%22open%22,%22userId%22:%22107317458065231631421%22%7D#G1c39hHC-_zPg2Y4fasHNSlGnUWOxVY4Bx)
Na parte de baixo tem duas abas, uma só com o modelo e outra com a análise que inclui as interferências e propagações
