### ISSUE TITLE
Criar iStar's do Habitica

### ISSUE THREAD

**Issue by devsalula** [requisitos-habitica/Habitica#86]
## Descrição da Issue
Criar o _iStar_, levando em consideração um modelo de Dependência e os modelos de _Rationale_, correlacionado aos autores.

**Comment by gabrielalbino** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/30835149/58431322-9d525300-8083-11e9-8d63-dff64cbb49ab.jpg)
![Untitled Diagram (1)](https://user-images.githubusercontent.com/30835149/58431325-9e838000-8083-11e9-86b4-c2f5838dea38.jpg)
![Untitled Diagram (2)](https://user-images.githubusercontent.com/30835149/58431326-9fb4ad00-8083-11e9-9ee2-738dd2c9f630.jpg)
![Untitled Diagram (3)](https://user-images.githubusercontent.com/30835149/58431327-a0e5da00-8083-11e9-9ad1-f8f2a549cd98.jpg)
![Untitled Diagram (4)](https://user-images.githubusercontent.com/30835149/58431329-a2170700-8083-11e9-8bde-e59aad49d8cd.jpg)

**Comment by Phe0** [comment]
V1 Diagrama de dependência Loja
![scanner_20190525_160737](https://user-images.githubusercontent.com/31973465/58431909-51ed7400-8086-11e9-9346-091156bef2b5.jpg)

V2 Diagrama de dependência Loja
![photo5136894969393555458](https://user-images.githubusercontent.com/31973465/58431929-6467ad80-8086-11e9-8d61-80e5ac7b626b.jpg)

V1 Rationale Loja
![photo5138721928222189598](https://user-images.githubusercontent.com/31973465/58431952-734e6000-8086-11e9-84c5-38ddd32caa4d.jpg)

V3 Diagrama de dependência Loja
![photo5141254296774486199](https://user-images.githubusercontent.com/31973465/58431963-7f3a2200-8086-11e9-847e-e391d562b682.jpg)

V2 Rationale Loja
![photo5141254296774486200](https://user-images.githubusercontent.com/31973465/58431975-8d883e00-8086-11e9-83f5-8c1a6244c0b6.jpg)

**Comment by devsalula** [comment]
Modelo de Dependência v2 e Rationale do Usuário.
![Dependencia-V2](https://user-images.githubusercontent.com/35435199/58433240-8f550000-808c-11e9-91d5-ae72fe6e345f.png)
![Rationale](https://user-images.githubusercontent.com/35435199/58433248-9aa82b80-808c-11e9-818d-8797f4a9d984.png)

**Comment by kaiquebuilds** [comment]
# V1 Desafios (SR e SD)
## SR - Criador Desafio V1
![Rationale Criador Desafio](https://user-images.githubusercontent.com/14828276/58439837-cdfab280-80ac-11e9-8606-2814edd2b020.png)

## SR - Participante Desafio V1
![Rationale Participante Desafio](https://user-images.githubusercontent.com/14828276/58439854-ecf94480-80ac-11e9-8cd4-c6c423adade8.png)

## SD V1
![SD Desafios](https://user-images.githubusercontent.com/14828276/58439861-fb476080-80ac-11e9-9819-21fde1c148b0.png)

**Comment by gabrielalbino** [comment]
# V2:
## Mudanças:
* Padronização dos títulos de metas, soft-metas, recursos e objetivos de acordo com a recomendação abaixo:
![image](https://user-images.githubusercontent.com/30835149/58519126-9b25ec80-8188-11e9-964b-8e0165dc06bf.png)
* Correção na troca de metas e objetivos
* Retirado artefatos confusos e sem sentido
* Melhor especificação nos artefatos necessários
## Artefatos:
![itarefas](https://user-images.githubusercontent.com/30835149/58519195-e04a1e80-8188-11e9-9545-2965e09b7ff4.png)
![itarefas (1)](https://user-images.githubusercontent.com/30835149/58519200-e2ac7880-8188-11e9-98bd-f912ac387e83.png)
![itarefas (2)](https://user-images.githubusercontent.com/30835149/58519202-e4763c00-8188-11e9-8029-9f2c6f9a0854.png)
