### ISSUE TITLE
Análise: Ágil

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#94]
## Descrição da Issue
Realizar a prototipação do produto definido pelo backlog confeccionado e verificar a consistência dos requisitos que foram modelados para ver se está realmente de acordo com o esperado (Habitica).

### Tasks:
- [x] Fazer protótipo em cima do Backlog
- [ ] Analisar o protótipo em relação ao Habitica

## Assignees
@gabrielalbino

**Comment by gabrielalbino** [comment]
Link do protótipo contendo quais historias de usuário e quais critérios de aceitação foram levados em consideração:
https://www.figma.com/file/XzKZo1x7myKuw5rTz3TPalLm/Habitica?node-id=0%3A1

**Comment by youssef-md** [comment]
Ficou muito bom como manteve a rastreabilidade

**Comment by gabrielalbino** [comment]
V2 do protótipo está disponível no mesmo link que postei anteriormente.
Além disso tá aqui o link do protótipo navegável: https://www.figma.com/proto/XzKZo1x7myKuw5rTz3TPalLm/Habitica?node-id=0%3A1&scaling=scale-down
